apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway-service
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080
  selector:
    service: gateway-service