apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway-service
  name: gateway-service
spec:
  ports:
      - port: 8080
        targetPort: 8080
  selector:
    service: gateway-service
