apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongo-service
  name: mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
#        network/internal: "true"
#        network/public: "true"
        service: mongo-service
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: authentication
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: postgres
            - name: MONGO_INITDB_ROOT_USERNAME
              value: postgres
          image: mongo
          name: mongo-service
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/mongo
              name: mongo-data
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data