apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  selector:
    service: elasticsearch
  ports:
    - port: 9200
      name: client
    - port: 9300
      name: node