apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kibana
  template:
    metadata:
      labels:
        service: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.10.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"
            - name: PACK_GRAPH_ENABLED
              value: "true"
            - name: XPACK_ML_ENABLED
              value: "true"
            - name: XPACK_MONITORING_ENABLED
              value: "true"
            - name: XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
              value: "true"
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-storage
              mountPath: "/usr/share/kibana/data"
      volumes:
        - name: kibana-storage
          persistentVolumeClaim:
            claimName: persistent-volume-claim