apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    service: logstash

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      service: logstash
  strategy: {}
  template:
    spec:
      containers:
        - env:
            - name: XPACK/MONITORING.ELASTICSEARCH.HOSTS
              value: http://elasticsearch:9200
          image: docker.elastic.co/logstash/logstash:7.10.0
          name: logstash
          ports:
            - containerPort: 5000
      restartPolicy: Always