apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongo
  name: mongo
spec:
  ports:
      - port: 27017
        targetPort: 27017
  selector:
    service: mongo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: mongo-data
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: authentication
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: postgres
            - name: MONGO_INITDB_ROOT_USERNAME
              value: postgres
          image: mongo
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/mongo
              name: mongo-data
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data