apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_DATABASE
              value: authentication
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: postgres
            - name: MONGO_INITDB_ROOT_USERNAME
              value: postgres
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: "/usr/share/mongo/data"
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: persistent-volume-claim