apiVersion: v1
kind: PersistentVolume
metadata:
    name: persistent-volume
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/mnt/services"