apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      service: account-service
  template:
    metadata:
      labels:
        service: account-service
    spec:
      containers:
        - name: account-service
          image: account-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            -   name: spring.data.mongodb.host
                value: mongo-service