apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres-service
  name: postgres-service
spec:
  ports:
    - name: "5430"
      port: 5430
      targetPort: 5432
  selector:
    service: postgres-service